source 'https://rubygems.org'

gem 'rails', '4.0.2'
gem 'sqlite3'
gem 'sass-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'jbuilder', '~> 1.2'
gem 'bootstrap-sass'
gem 'bcrypt-ruby', '~> 3.1.2', require: 'bcrypt'

group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'annotate'
end

group :doc do
  gem 'sdoc', require: false
end